title: Farset Labs
description: "Northern Ireland's Hackerspace"
tags: "hackerspace, makerspace, belfast, technology, maker movement"
markdown: kramdown
exclude: [README.md, _scripts, Gemfile, Gemfile.lock, etc, bin, makefile, buildout.cfg, bootstrap.py, requirements.txt]
plugins_dir: ./_plugins
base: ""
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
paginate_path: "news/page:num"
paginate: 5
url: "https://www.farsetlabs.org.uk"
social:
  github: "https://www.github.com/FarsetLabs"
  facebook: "https://www.facebook.com/FarsetLabs"
  twitter: "https://www.twitter.com/FarsetLabs"
  flickr: "https://www.flickr.com/groups/farset_labs"
  blogfeed: "https://blog.farsetlabs.org.uk/feed/"
  chat: "https://farsetlabs.org.uk/slack"
  twitch: "https://www.twitch.tv/farsetlabs"
links:
  - name: Blog
    url: "https://blog.farsetlabs.org.uk/"
  - name: Social
    url: ""
    list:
    - name: Facebook
      url: "https://facebook.com/FarsetLabs"
    - name: Twitter
      url: "https://twitter.com/FarsetLabs"
    - name: Slack
      url: "https://farsetlabs.org.uk/slack"
    - name: Blog
      url: "https://blog.farsetlabs.org.uk/feed/"
    - name: Flickr
      url: "https://www.flickr.com/groups/farset_labs"
officers:
  - name: Andrew Bolster
    username: bolster
    year: 2011 -
    title: "Director/Founder"
    blurb: "Autonomous Systems Researcher, Consultant, Speaker, and Enfant Terrible. You can see some of his work over on [his website](https://andrewbolster.info)."
    email: "bolster@farsetlabs.org.uk"
    twitter: "bolster"
    website: "https://andrewbolster.info"
    facebook: "andrewbolster"
    linkedin: "andrewbolster"
    github: "andrewbolster"
    discourse: "bolster"

  - name: Dylan Wylie
    username: wylie
    year: 2013 -
    title: "Director"
    blurb: "Co-founder of rapidly growing health consultancy startup,  [We Slim Together](https://www.weslimtogether.co.uk), physicist, developer & technologist."
    email: "dylan@farsetlabs.org.uk"
    twitter: "dylwylie"
    discourse: "dylan"

  - name: Colin Mitchell
    username: pixelpage
    year: 2016 -
    title: "Director"
    blurb: "Business Technology Advisor, interim CTO & troubleshooter/causer, hands-on code-tweaker, occasional blues guitarist."
    email: "colin.mitchell@farsetlabs.org.uk"
    twitter: "pixelpage"
    linkedin: "colinmitch"

  - name: Artemiy Kondratiev
    username: art
    year: 2018 -
    title: "Director"
    blurb: "Software engineer, public speaker and event organiser."
    email: "art@farsetlabs.org.uk"
    twitter: "awflwafl"
    linkedin: "artemiy-kondratiev"
    github: "awflwafl"

  - name: Daniel Porter
    username: porter
    year: 2014 -
    title: "Digital Infrastructure NEM"
    email: "digitalinfrastructure@farsetlabs.org.uk"
    discourse: "stealthii"
    blurb: "Daniel makes the bits go around."
    twitter: "stealthii"
    github: "stealthii"

  - name: Glenn Davidson
    username: davidson
    year: 2014 -
    title: "Events NEM"
    blurb: "Glenn is an enthusiastic software engineer with 10 years experience in business problem analysis, enterprise systems, and mobile technology.  While currently working on cutting-edge start-up and mobile projects as part of [Coding Fury Ltd](https://www.codingfury.com/), he also organises local events for Ireland's independent game industry. Glenn is the central point of contact for Farsets event scheduling and logistics."
    email: "events@farsetlabs.org.uk"
    discourse: "panloaf"
    twitter: "glenndavidson"
    facebook: "panloaf"
    website: "https://blitter.co.uk"
    linkedin: "glennrdavidson"

  - name: Claire Wilgar
    username: wilgar
    year: 2015 -
    title: "Community NEM"
    blurb: "Claire is a senior frontend developer and organiser of Girl Geeks Belfast and co-organiser of Global Game Jam and BelfastJS, and is the point of contact for member and community issues and queries in Farset Labs."
    email: "community@farsetlabs.org.uk"
    discourse: "clairebones"
    twitter: "clairedotw"

  - name: Phil Weir
    username: philtweir
    year: 2018 -
    title: "Co-Working NEM"
    email: coworking@farsetlabs.org.uk
    twitter: "phil_t_weir"
    github: "philtweir"
    website: "https://flaxandteal.co.uk"
    linkedin: "phil-weir-033b5a62"
    blurb: "Focused on open technology and its ability to transform business and society, through efficiency and interlinking. Development experience in web technologies and numerical simulation, primarily with backend services, alongside cloud (AWS) and systems administration."


