name: Farset Labs
description: "Northern Ireland's Hackerspace"
tags: "hackerspace, makerspace, belfast, technology, maker movement"
pygments: true
markdown: kramdown
exclude: [README.md, _scripts, Gemfile, Gemfile.lock, etc, bin, makefile, buildout.cfg, bootstrap.py, requirements.txt]
plugins: ./_plugins
base: ""
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
paginate_path: "news/page:num"
paginate: 5
url: "http://www.farsetlabs.org.uk"
social:
  github: FarsetLabs
  facebook: FarsetLabs
  gplus: FarsetLabsOrgUk
  twitter: FarsetLabs
  flickr: groups/farset_labs
  blogfeed: "http://blog.farsetlabs.org.uk/feed/"
  forum: "http://discourse.farsetlabs.org.uk/"
links:
  - name: Blog
    url: "http://blog.farsetlabs.org.uk/"
  - name: Social
    url: ""
    list:
    - name: Facebook
      url: "http://facebook.com/FarsetLabs"
    - name: Twitter
      url: "http://twitter.com/FarsetLabs"
    - name: Forum
      url: "http://discourse.farsetlabs.org.uk/"
    - name: Flickr
      url: "http://www.flickr.com/groups/farset_labs"
    - name: Wiki
      url: "http://wiki.farsetlabs.org.uk/"
officers:
  - name: Andrew Bolster
    username: bolster
    year: 2011 -
    title: "Director/Founder"
    blurb: "Autonomous Systems Researcher, Consultant, Speaker, and Enfant Terrible. You can see some of his work over on [his website](http://andrewbolster.info)"
    email: "bolster@farsetlabs.org.uk"
    twitter: "bolster"
    website: "http://andrewbolster.info"
    facebook: "andrewbolster"
    linkedin: "andrewbolster"
    github: "andrewbolster"
    discourse: "bolster"

  - name: David Kane
    username: kane
    year: 2011 -
    title: "Director/Founder"
    blurb: "Postgraduate researcher specialising in condensed matter physics, embedded developer and all round good guy."
    email: "david@farsetlabs.org.uk"
    twitter: "dsrkane"
    discourse: "kane"

  - name: Dylan Wylie
    username: wylie
    year: 2013 -
    title: "Director"
    blurb: "Co-founder of rapidly growing health consultancy startup,  [We Slim Together](http://www.weslimtogether.co.uk), physicist, developer & technologist."
    email: "dylan@farsetlabs.org.uk"
    twitter: "dylwylie"
    discourse: "dylan"

  - name: Conor Robinson
    username: robinson
    year: 2014 -
    title: "Director"
    blurb: "Electrical and Electronic Engineer, Amateur Radio Course Tutor, Red Cross First Aider. Fixes stuff that's broken"
    email: "conor@farsetlabs.org.uk"
    discourse: "conor"
    linkedin: "conorrobinson"

  - name: Pip Shea
    username: shealo
    year: 2015 -
    title: "Director"
    blurb: "Digital Media Researcher, Designer, and Educator."
    email: "pip@farsetlabs.org.uk"
    discourse: "pip"
    twitter: "shealo"
    website: "http://www.pipshea.net/"
    linkedin: "pipshea"

  - name: Daniel Porter
    username: porter
    year: 2014 -
    title: "Digital Infrastructure NEM"
    email: "digitalinfrastructure@farsetlabs.org.uk"
    discourse: "stealthii"
    blurb: "Daniel makes the bits go around"
    twitter: "stealthii"
    github: "stealthii"

  - name: Glenn Davidson
    username: davidson
    year: 2014 -
    title: "Events NEM"
    blurb: "Glenn is an enthusiastic software engineer with 10 years experience in business problem analysis, enterprise systems, and mobile technology.  While currently working on cutting-edge start-up and mobile projects as part of [Coding Fury Ltd](http://www.codingfury.com/), he also organises local events for Ireland's independent game industry. Glenn is the central point of contact for Farsets event scheduling and logistics"
    email: "events@farsetlabs.org.uk"
    discourse: "panloaf"
    twitter: "glenndavidson"
    facebook: "panloaf"
    website: "http://blitter.co.uk"
    linkedin: "glennrdavidson"

  - name: Colin Kelsey
    username: kelsey
    year: 2015 -
    title: "Project Room NEM"
    blurb: "Research scientist with a PhD in Plasma Physics and a particular interest in medical applications.  Also homebrewer, DIY enthusiast and general hands-on person for building or fixing anything in the workshop that needs built or fixed."
    email: "projects@farsetlabs.org.uk"
    linkedin: "colinkelsey"
    facebook: "colin.kelsey"
    discourse: "colin"

  - name: Claire Wilgar
    username: wilgar
    year: 2015 -
    title: "Community NEM"
    blurb: "Claire is a software developer at [Servasport](http://www.servasport.com/), and is the point of contact for resourcing and equipment issues related to member projects in the space."
    email: "community@farsetlabs.org.uk"
    discourse: "clairebones"
    twitter: "clairedotw"

  - name: Andrew Mulholland
    username: mulholland
    year: 2015 -
    title: "Outreach NEM"
    email: "outreach@farsetlabs.org.uk"
    blurb: "Award winning Inventor, Raspberry Pi expert, Computer Science teacher, STEMNET Ambassador, UK TalkTalk Digital Hero 2014 and @PiNetDev developer."
    discourse: "gbaman1"
    twitter: "gbaman1"
    website: "http://pi.gbaman.info/"

  - name: Ben Bland
    username: bland
    year: 2015 -
    title: "Development NEM"
    blurb: "Digital strategist (purveyor of fine bullshit). 10 years’ web marcomms & business. Loves science, technology, ecology & travel. Writer, filmmaker, photographer"
    email: "development@farsetlabs.org.uk"
    twitter: "ben_bland"
    discourse: "ben"

